import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VanishMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" 
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Humne body ke andar font classes ko explicitly add kar diya hai */}
      <body 
        className={`${geistSans.className} ${geistMono.variable} min-h-full flex flex-col`} 
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}